# Automatically generated by configure - do not modify
SRC_PATH=/mnt/ext1_1TB/ikhwan/driller/afl-2.52b/qemu_mode/qemu-2.10.0/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
